export const FREE_STAGES_PER_CATEGORY = 2;
export const STAGES_PER_CATEGORY = 30;
export const QUESTIONS_PER_STAGE = 3;

export const TOTAL_QUESTIONS_PER_CATEGORY = STAGES_PER_CATEGORY * QUESTIONS_PER_STAGE;
export const TOTAL_QUESTIONS = TOTAL_QUESTIONS_PER_CATEGORY * 8;
