const l = (de, en) => ({ de, en });
// Each row is a distinct observation: a name, a clue, and a concrete relationship.
// Incorrect pictures deliberately come from unrelated concepts, not plausible alternatives.
const topics = [
// id, picture, name DE/EN, group, clue DE/EN, relationship question DE/EN, correct picture/name DE/EN, wrong picture/name DE/EN
['sun','☀️','Sonne','sun','sky','Sie wärmt die Erde und macht den Tag hell.','It warms Earth and makes the day bright.','Was schützt deine Augen bei hellem Sonnenschein?','What protects your eyes in bright sunshine?','🕶️','Sonnenbrille','sunglasses','🧤','Handschuhe','gloves'],
['rain','🌧️','Regen','rain','weather','Viele Wassertropfen fallen aus einer Wolke.','Many drops of water fall from a cloud.','Was hält Regen von deinem Kopf fern?','What keeps rain off your head?','☂️','Regenschirm','umbrella','🪮','Kamm','comb'],
['snow','❄️','Schnee','snow','weather','Die Flocken sind kalt und können auf dem Boden liegen bleiben.','The flakes are cold and can settle on the ground.','Was kannst du aus Schnee bauen?','What can you build out of snow?','☃️','Schneemann','snowman','🪁','Drachen','kite'],
['wind','💨','Wind','wind','weather','Du kannst ihn fühlen. Er bewegt Blätter und Zweige.','You can feel it. It moves leaves and branches.','Was kann der Wind am Himmel tragen?','What can the wind lift into the sky?','🪁','Drachen','kite','🪨','Stein','stone'],
['rainbow','🌈','Regenbogen','rainbow','weather','Ein bunter Bogen erscheint manchmal, wenn Sonne auf Regentropfen scheint.','A colorful arc sometimes appears when sunlight shines on raindrops.','Was braucht ein Regenbogen außer Regentropfen?','What does a rainbow need besides raindrops?','☀️','Sonnenlicht','sunlight','🔦','Taschenlampe','flashlight'],
['cloud','☁️','Wolke','cloud','weather','Viele winzige Wassertröpfchen oder Eiskristalle schweben zusammen am Himmel.','Tiny water droplets or ice crystals float together in the sky.','Was kann aus einer dunklen Wolke fallen?','What can fall from a dark cloud?','💧','Regentropfen','raindrops','🍎','Äpfel','apples'],
['spring','🌷','Frühling','spring','season','Nach dem Winter wird es wärmer und viele Blumen beginnen zu blühen.','After winter it gets warmer and many flowers begin to bloom.','Welche Blume blüht bei uns oft im Frühling?','Which flower often blooms here in spring?','🌷','Tulpe','tulip','🌻','Sonnenblume','sunflower'],
['summer','🏖️','Sommer','summer','season','Zwischen Frühling und Herbst sind die Tage bei uns besonders lang.','Between spring and fall, our days are especially long.','Was schützt deinen Kopf an einem heißen Sommertag?','What protects your head on a hot summer day?','👒','Sonnenhut','sun hat','🧦','Socken','socks'],
['autumn','🍂','Herbst','fall','season','Nach dem Sommer werden viele Blätter bunt und fallen von den Bäumen.','After summer, many leaves change color and fall from trees.','Was liegt im Herbst oft unter einem Laubbaum?','What often lies under a leafy tree in fall?','🍂','Laub','fallen leaves','🐚','Muscheln','seashells'],
['winter','☃️','Winter','winter','season','Nach dem Herbst sind die Tage kurz. Draußen kann es sehr kalt werden.','After fall, the days are short. It can get very cold outside.','Was hält deine Hände im Winter warm?','What keeps your hands warm in winter?','🧤','Handschuhe','gloves','🕶️','Sonnenbrille','sunglasses'],
['tree','🌳','Baum','tree','plant','Er hat einen festen Stamm und viele Äste.','It has a sturdy trunk and many branches.','Was wächst an den Zweigen eines Laubbaums?','What grows on the twigs of a leafy tree?','🍃','Blätter','leaves','🐚','Muscheln','seashells'],
['flower','🌸','Blume','flower','plant','Ihre bunten Blüten locken oft Bienen an.','Its colorful blossoms often attract bees.','Was besucht Blüten, um Nektar zu sammeln?','What visits blossoms to collect nectar?','🐝','Biene','bee','🐟','Fisch','fish'],
['seedling','🌱','Keimling','seedling','plant','Aus einem Samen wächst eine kleine neue Pflanze.','A small new plant grows from a seed.','Was braucht ein Keimling zum Wachsen außer Licht?','What does a seedling need to grow besides light?','💧','Wasser','water','🧼','Seife','soap'],
['cactus','🌵','Kaktus','cactus','plant','Diese Pflanze speichert Wasser und hat oft Stacheln.','This plant stores water and often has spines.','Wo können viele Kakteen gut wachsen?','Where can many cacti grow well?','🏜️','In der Wüste','in the desert','🌊','Im Meer','in the sea'],
['sunflower','🌻','Sonnenblume','sunflower','plant','Diese große Blume hat meist gelbe Blütenblätter und eine dunkle Mitte.','This tall flower usually has yellow petals and a dark center.','Wo findest du die Kerne einer Sonnenblume?','Where do you find sunflower seeds?','🌻','Im Blütenkopf','in the flower head','☁️','In einer Wolke','in a cloud'],
['tulip','🌷','Tulpe','tulip','plant','Diese Frühlingsblume wächst aus einer Zwiebel und hat eine kelchförmige Blüte.','This spring flower grows from a bulb and has a cup-shaped bloom.','Welche Jahreszeit passt zur Tulpenblüte bei uns?','Which season matches tulip blooms here?','🌷','Frühling','spring','☃️','Winter','winter'],
['evergreen','🌲','Nadelbaum','evergreen tree','plant','Seine Blätter sind schmale Nadeln. Viele bleiben im Winter grün.','Its leaves are narrow needles. Many stay green in winter.','Was findest du an einer Kiefer?','What can you find on a pine tree?','🌲','Nadeln','needles','🌸','Rosa Blüten','pink blossoms'],
['palm','🌴','Palme','palm tree','plant','Oben an ihrem Stamm wachsen lange große Blätter wie ein Schopf.','Long, large leaves grow like a crown at the top of its trunk.','Welche Frucht kann an einer Kokospalme wachsen?','Which fruit can grow on a coconut palm?','🥥','Kokosnuss','coconut','🍓','Erdbeere','strawberry'],
['leaf','🍃','Blatt','leaf','part','Dieser grüne Pflanzenteil fängt Sonnenlicht ein.','This green plant part catches sunlight.','Was braucht ein grünes Blatt, um Nahrung für die Pflanze herzustellen?','What does a green leaf need to make food for the plant?','☀️','Sonnenlicht','sunlight','🧊','Eiswürfel','ice cubes'],
['seed','🫘','Samen','seed','part','In ihm steckt der Anfang einer neuen Pflanze.','It holds the beginning of a new plant.','Was kann aus einem Bohnensamen wachsen?','What can grow from a bean seed?','🌱','Neue Pflanze','new plant','🪨','Stein','stone'],
['mountain','⛰️','Berg','mountain','land','Er ragt hoch über die Landschaft hinaus und hat einen Gipfel.','It rises high above the landscape and has a peak.','Wie nennt man die höchste Stelle eines Berges?','What is the highest point of a mountain called?','⛰️','Gipfel','peak','🏖️','Strand','beach'],
['sea','🌊','Meer','sea','land','Eine riesige Fläche aus salzigem Wasser.','A huge area of salty water.','Wie schmeckt Meerwasser?','What does seawater taste like?','🧂','Salzig','salty','🍯','Süß','sweet'],
['forest','🌳🌲','Wald','forest','land','Viele Bäume wachsen hier dicht beieinander.','Many trees grow close together here.','Was wächst in einem Wald besonders häufig?','What grows especially often in a forest?','🌳','Bäume','trees','🌵','Kakteen','cacti'],
['desert','🏜️','Wüste','desert','land','Hier fällt sehr wenig Regen. Manche sind sandig, andere steinig.','Very little rain falls here. Some are sandy, others rocky.','Was fehlt in einer Wüste besonders oft?','What is especially scarce in a desert?','💧','Wasser','water','☀️','Sonnenlicht','sunlight'],
['island','🏝️','Insel','island','land','Dieses Stück Land ist auf allen Seiten von Wasser umgeben.','This piece of land has water on every side.','Was umgibt eine Insel?','What surrounds an island?','🌊','Wasser','water','🛣️','Straßen','roads'],
['moon','🌙','Mond','moon','sky','Er umkreist die Erde und leuchtet mit dem Licht der Sonne.','It goes around Earth and shines with light from the sun.','Woher kommt das Licht, das der Mond zurückwirft?','Where does the light reflected by the moon come from?','☀️','Von der Sonne','from the sun','🔦','Von einer Lampe','from a lamp'],
['star','⭐','Stern','star','sky','Am Nachthimmel sieht er winzig aus, obwohl er sehr weit weg und groß ist.','It looks tiny in the night sky, although it is far away and large.','Wann kannst du die meisten Sterne gut sehen?','When can you see most stars clearly?','🌃','Bei dunkler Nacht','on a dark night','🌅','Bei hellem Tag','in bright daylight'],
['stone','🪨','Stein','stone','material','Er ist hart. Du findest ihn zum Beispiel auf einem steinigen Weg.','It is hard. You might find it on a rocky path.','Woraus bestehen viele Berge?','What are many mountains made of?','🪨','Gestein','rock','🧸','Kuscheligem Stoff','soft fabric'],
['wood','🪵','Holz','wood','material','Dieses feste Material stammt aus dem Stamm und den Ästen von Bäumen.','This firm material comes from tree trunks and branches.','Woher kommt Holz?','Where does wood come from?','🌳','Von Bäumen','from trees','🌊','Aus dem Meer','from the sea'],
['mushroom','🍄','Pilz','mushroom','fungus','Dieser Pilz hat einen Stiel und einen Hut. Er kann im Wald wachsen.','This mushroom has a stalk and a cap. It can grow in a forest.','Was machst du mit einem unbekannten Pilz im Wald?','What do you do with an unfamiliar mushroom in the forest?','👀','Nur anschauen','only look at it','🍽️','Essen','eat it'],
];
const groups = {
 weather: ['Wetter','weather','🌦️'], season:['Jahreszeit','season','🍂'], plant:['Pflanze','plant','🌱'],
 part:['Pflanzenteil','plant part','🍃'], land:['Landschaft','landscape','⛰️'], sky:['Himmelskörper','object in space','🌙'], material:['Naturmaterial','natural material','🪨'], fungus:['Pilz','fungus','🍄'],
};
const rotate=(a,n)=>a.slice(n%a.length).concat(a.slice(0,n%a.length));
module.exports=function buildNature(age){
 const result=[];
 for(let i=0;i<topics.length;i++){
  const [id,picture,de,en,group,clueDe,clueEn,relDe,relEn,relPic,relNameDe,relNameEn,badPic,badDe,badEn]=topics[i];
  const others=[topics[(i+7)%topics.length],topics[(i+17)%topics.length]];
  const add=(prompt,visual,answers,correct,success,hint)=>result.push({id:`nature-${age}-${result.length+1}`,prompt,visual,answers:rotate(answers,result.length),correctAnswerId:correct,success,hint,conceptKey:id});
  if(age==='discoverer'){
   add(l(`Finde dieses Bild: ${de}.`,`Find this picture: ${en}.`),'',[{id,label:picture},{id:others[0][0],label:others[0][1]}],id,l(`Ja! Das ist das Bild für: ${de}.`,`Yes! This is the picture for: ${en}.`),l('Schau dir die beiden Bilder genau an.','Look closely at both pictures.'));
   add(l(`Was ist gemeint? ${clueDe}`,`What is it? ${clueEn}`),'',[{id,label:picture},{id:others[1][0],label:others[1][1]}],id,l(`Gut zugehört! ${de} passt.`,`Good listening! ${en} fits.`),l('Höre auf den Hinweis und vergleiche die Bilder.','Listen to the clue and compare the pictures.'));
   add(l(relDe,relEn),picture,[{id:'related',label:relPic},{id:'unrelated',label:badPic}],'related',l(`Richtig: ${relNameDe}.`,`Correct: ${relNameEn}.`),l('Welches Bild passt zu der Frage?','Which picture fits the question?'));
  }else{
   add(l(`Navis Natur-Rätsel: ${clueDe}`,`Navi’s nature riddle: ${clueEn}`),'',[{id,label:l(de,en)},...others.map(o=>({id:o[0],label:l(o[2],o[3])}))],id,l(`Richtig erkannt: ${de}.`,`Well spotted: ${en}.`),l('Welche Antwort passt zu allen Eigenschaften?','Which answer fits all the clues?'));
   const groupIds=[group,...Object.keys(groups).filter(k=>k!==group&&!(group==='plant'&&k==='part')&&!(group==='part'&&k==='plant')).slice(0,2)];
   add(l(`Zu welcher Gruppe gehört: ${de}?`,`Which group does ${en} belong to?`),picture,groupIds.map(k=>({id:k,label:l(groups[k][0],groups[k][1])})),group,l(`${de} gehört zur Gruppe: ${groups[group][0]}.`,`${en} belongs in the group: ${groups[group][1]}.`),l('Denke daran, was das Bild zeigt und wo du es findest.','Think about what the picture shows and where you find it.'));
   add(l(`Denke weiter: ${relDe}`,`Think a little further: ${relEn}`),picture,[{id:'related',label:l(relNameDe,relNameEn)},{id:'unrelated',label:l(badDe,badEn)},{id:'toy',label:l('Spielzeugauto','toy car')}],'related',l(`Genau: ${relNameDe}.`,`Exactly: ${relNameEn}.`),l('Nutze dein Wissen über die Natur.','Use what you know about nature.'));
  }
 }
 return result;
};
